#pragma once

#define PHYSBOX_WINDOW_WIDTH 1600
#define PHYSBOX_WINDOW_HEIGHT 900
#define PHYSBOX_TARGET_FPS 60

#define PHYSBOX_SHADOW_MAP_RESOLUTION 4096
#define PHYSBOX_SHADOW_MAP_WIDTH 4096
#define PHYSBOX_SHADOW_MAP_HEIGTH 4096

#define PHYSBOX_MAX_LIGHTS 4

#define PHYSBOX_SLEEP_EPSILON 0.4f